#!/bin/bash
# This is a simple post deploy hook executed after your application
# is deployed and started.  This script gets executed directly, so
# it could be python, php, ruby, etc.
REPO_PATH="../../app-root/repo"

echo "Updating facets..."
cd $REPO_PATH
node script/import_facets.js

echo "Updating neighborhoods..."
node script/import_hoods.js

echo "Updating scores..."
node script/import_scores.js
